import type { InnovationSignal, RadarRelation, RadarReview, RadarCluster } from './types';

export const demoSignals: InnovationSignal[] = [
  {
    id: 'demo-1',
    title: 'Campus as an AI Sandbox: Open-Source Smart Building Infrastructure for Agentic AI Education',
    summary: 'An open-source, five-layer smart-building platform turns campus infrastructure such as lighting, HVAC, elevators and energy systems into a student-modifiable environment for project-based agentic AI learning.',
    source_url: 'https://events.educause.edu/annual-conference/2026/agenda/campus-as-an-ai-sandbox-opensource-smart-building-infrastructure-for-agentic-ai-education',
    source_name: 'EDUCAUSE 2026 / University of Electro-Communications',
    source_type: 'conference_poster',
    published_at: '2026-09-30T00:00:00Z',
    discovered_at: '2026-10-02T08:00:00Z',
    country: 'Japan',
    country_code: 'JP',
    city: 'Tokyo',
    latitude: 35.6762,
    longitude: 139.6503,
    innovation_type: 'Learning Environment',
    educational_problem: 'Abstract STEM exercises disconnected from tangible real-world systems and immediate ecological consequences.',
    target_groups: ['Higher Education', 'Sekundarstufe II', 'Vocational Education'],
    novelty: 4,
    maturity: 'pilot',
    evidence_level: 'case',
    evidence_summary: 'Official EDUCAUSE session materials describe the five-layer platform and student-designed/deployed agentic AI applications across campus buildings. The public session page does not report comparative learning-outcome metrics.',
    swiss_relevance: 'High alignment with Swiss MINT initiatives and Lehrplan 21 interdisciplinary "Natur und Technik" (Sek I/II), especially for cantonal gymnasium living labs.',
    swiss_application_hypothesis: 'Instrument a pilot classroom cluster in a Bernese vocational school with open IoT telemetry; students examine heating efficiency trade-offs during winter quarters.',
    limitations: 'Demands close collaboration with facility management, strict student data privacy partitioning, and robust API maintenance.',
    tags: ['living lab', 'IoT telemetry', 'authentic inquiry', 'STEM'],
    status: 'candidate'
  },
  {
    id: 'demo-2',
    title: 'Mission-Based AI Skills Studio (Artifact-Centric)',
    summary: 'Learners tackle scoped, multi-stage workplace simulations with contemporary AI tooling, evaluated solely on verifiable artifacts and rationales rather than multiple-choice comprehension.',
    source_url: '#',
    source_name: 'Illustrative demonstrator scenario — not a verified innovation record',
    source_type: 'illustrative_demo',
    published_at: null,
    discovered_at: '2026-10-01T08:00:00Z',
    country: 'United States',
    country_code: 'US',
    city: 'San Francisco',
    latitude: 37.7749,
    longitude: -122.4194,
    innovation_type: 'Pedagogy',
    educational_problem: 'Severe divergence between passive online video completion and actual problem-solving agency in complex generative toolchains.',
    target_groups: ['Vocational Education', 'Higher Education', 'Teacher Education'],
    novelty: 4,
    maturity: 'pilot',
    evidence_level: 'none',
    evidence_summary: 'Synthetic scenario used to exercise geography, clustering, filtering and Innovation Profile UI. It is not a verified research finding and must not be cited as evidence.',
    swiss_relevance: 'Directly applicable to the dual vocational education system (Berufslehre) and PHBern pre-service teacher media competence training.',
    swiss_application_hypothesis: 'Refactor one module of the Berufsmaturität ICT curriculum from standard slide presentations to a four-stage verified artifact portfolio challenge.',
    limitations: 'Observable artifacts do not guarantee deep theoretical understanding without systematic debriefing and oral defense.',
    tags: ['mission learning', 'dual education', 'artifact-driven', 'assessment', 'illustrative demo'],
    status: 'candidate'
  },
  {
    id: 'demo-3',
    title: 'Image-First Multilingual Early Literacy Interface',
    summary: 'A pedagogical approach for early literacy that anchors phoneme-grapheme acquisition in familiar cultural visual objects before introducing textual grammar, minimizing cognitive abstraction.',
    source_url: '#',
    source_name: 'Illustrative demonstrator scenario — not a verified innovation record',
    source_type: 'illustrative_demo',
    published_at: null,
    discovered_at: '2026-10-02T07:00:00Z',
    country: 'India',
    country_code: 'IN',
    city: 'Raipur',
    latitude: 21.2514,
    longitude: 81.6296,
    innovation_type: 'Teaching Method',
    educational_problem: 'Steep cognitive barrier in early symbol decoding for children entering primary school without prior home-language literacy support.',
    target_groups: ['Primary / Early Childhood (Zyklus 1)'],
    novelty: 3,
    maturity: 'experiment',
    evidence_level: 'none',
    evidence_summary: 'Synthetic scenario used to exercise geography, clustering, filtering and Innovation Profile UI. It is not a verified research finding and must not be cited as evidence.',
    swiss_relevance: 'Valuable reference for Swiss integration classes (DaZ - Deutsch als Zweitsprache) in urban cantonal primary schools.',
    swiss_application_hypothesis: 'Test whether visual semantic anchoring accelerates initial phonetic decoding among multilingual Zyklus 1 students in Biel/Bienne school districts.',
    limitations: 'Dependent on cultural familiarity of images; risk of delaying orthographic consolidation if transition to text is not carefully timed.',
    tags: ['early literacy', 'DaZ', 'multilingual', 'Zyklus 1', 'illustrative demo'],
    status: 'candidate'
  },
  {
    id: 'demo-4',
    title: 'ArgueMate: AI Debating Agent for Learning Through Argumentation',
    summary: 'A BeLEARN/EPFL project exploring an AI-powered debate partner that adapts its stance and argumentative style to support structured student argumentation.',
    source_url: 'https://learn.epfl.ch/en/initiatives/belearn/',
    source_name: 'EPFL LEARN / BeLEARN — ArgueMate',
    source_type: 'research_project',
    published_at: null,
    discovered_at: '2026-10-01T14:30:00Z',
    country: 'Switzerland',
    country_code: 'CH',
    city: 'Lausanne',
    latitude: 46.5197,
    longitude: 6.5668,
    innovation_type: 'Pedagogy',
    educational_problem: 'Students passively trusting and copying generative AI answers rather than developing critical epistemic verification habits.',
    target_groups: ['Sekundarstufe II', 'Higher Education', 'Teacher Education'],
    novelty: 5,
    maturity: 'experiment',
    evidence_level: 'none',
    evidence_summary: 'The public BeLEARN/EPFL project page describes ArgueMate and its pedagogical intent, but the project summary used for this demonstrator does not state controlled learning-outcome results or effect sizes.',
    swiss_relevance: 'High domestic relevance. Built directly within the Swiss higher education research ecosystem with clear pathways into cantonal gymnasia.',
    swiss_application_hypothesis: 'Integrate the triadic adversarial model into a Sek II history & philosophy seminar in Canton Bern, evaluating whether students identify synthetic historical fallacies.',
    limitations: 'High dependency on prompt boundary control to avoid reinforcing student misconceptions if the AI is too convincing.',
    tags: ['critical thinking', 'epistemic agency', 'Switzerland', 'collaborative learning'],
    status: 'candidate'
  },
  {
    id: 'demo-5',
    title: 'Adaptive Cognitive Load Micro-Scaffolder',
    summary: 'Real-time eye-tracking and response-latency analysis inside an open mathematical problem solver that dynamically collapses auxiliary formulas when cognitive overload is detected.',
    source_url: '#',
    source_name: 'Illustrative demonstrator scenario — not a verified innovation record',
    source_type: 'illustrative_demo',
    published_at: null,
    discovered_at: '2026-09-28T09:15:00Z',
    country: 'Australia',
    country_code: 'AU',
    city: 'Melbourne',
    latitude: -37.8136,
    longitude: 144.9631,
    innovation_type: 'Learning Analytics',
    educational_problem: 'One-size-fits-all problem step hints causing either cognitive boredom for advanced students or affective frustration for struggling peers.',
    target_groups: ['Sekundarstufe I', 'Sekundarstufe II'],
    novelty: 4,
    maturity: 'experiment',
    evidence_level: 'none',
    evidence_summary: 'Synthetic scenario used to exercise geography, clustering, filtering and Innovation Profile UI. It is not a verified research finding and must not be cited as evidence.',
    swiss_relevance: 'Relevant to differentiated instruction mandated in Lehrplan 21 for heterogeneous secondary classes.',
    swiss_application_hypothesis: 'Adapt the latency-triggered scaffolding heuristics to open web-based geometry proof tools used in Bernese Sek I classrooms.',
    limitations: 'Sensors like eye-trackers raise privacy and cost barriers; latency-only fallbacks are noisy and prone to false interventions.',
    tags: ['cognitive load', 'adaptive scaffolding', 'mathematics', 'Sek I', 'illustrative demo'],
    status: 'candidate'
  },
  {
    id: 'demo-6',
    title: 'Continuous Formative Speech Assessment for Language Learners',
    summary: 'A low-latency on-device acoustic model that provides formative prosody and phonetic feedback during spontaneous dialogue simulations without storing biometric voice recordings in cloud vaults.',
    source_url: '#',
    source_name: 'Illustrative demonstrator scenario — not a verified innovation record',
    source_type: 'illustrative_demo',
    published_at: null,
    discovered_at: '2026-09-30T11:00:00Z',
    country: 'Finland',
    country_code: 'FI',
    city: 'Helsinki',
    latitude: 60.1699,
    longitude: 24.9384,
    innovation_type: 'Assessment',
    educational_problem: 'Teachers in 25-student language classrooms lack time to give immediate, individualized oral pronunciation feedback to every learner.',
    target_groups: ['Primary', 'Sekundarstufe I'],
    novelty: 3,
    maturity: 'pilot',
    evidence_level: 'none',
    evidence_summary: 'Synthetic scenario used to exercise geography, clustering, filtering and Innovation Profile UI. It is not a verified research finding and must not be cited as evidence.',
    swiss_relevance: 'Directly beneficial for second-language acquisition (French/German) in Swiss compulsory schooling.',
    swiss_application_hypothesis: 'Test privacy-compliant local edge models for oral French practice in German-speaking Bernese primary schools.',
    limitations: 'May penalize non-standard dialects or non-pathological speech impediments if reference acoustic baselines are overly rigid.',
    tags: ['language learning', 'formative assessment', 'edge AI', 'privacy', 'illustrative demo'],
    status: 'candidate'
  },
  {
    id: 'demo-7',
    title: 'National Open Educational AI Tutor Scaffold',
    summary: 'A state-curated, syllabus-aligned bilingual pedagogical agent co-designed with teacher unions to tutor students through national curriculum benchmarks without commercial vendor lock-in.',
    source_url: '#',
    source_name: 'Illustrative demonstrator scenario — not a verified innovation record',
    source_type: 'illustrative_demo',
    published_at: null,
    discovered_at: '2026-09-25T16:00:00Z',
    country: 'Singapore',
    country_code: 'SG',
    city: 'Singapore',
    latitude: 1.3521,
    longitude: 103.8198,
    innovation_type: 'Curriculum & Governance',
    educational_problem: 'Inequitable access to high-priced private AI tutoring subscriptions widening the socioeconomic achievement gap.',
    target_groups: ['Sekundarstufe I', 'Sekundarstufe II'],
    novelty: 4,
    maturity: 'scaling',
    evidence_level: 'none',
    evidence_summary: 'Synthetic scenario used to exercise geography, clustering, filtering and Innovation Profile UI. It is not a verified research finding and must not be cited as evidence.',
    swiss_relevance: 'Exemplary for Swiss cantonal sovereignty discussions and Edu-R&D consortia (e.g. Educa, BeLEARN) seeking sovereign public digital infrastructure.',
    swiss_application_hypothesis: 'Explore an open-source, Lehrplan-21-grounded retrieval model shared across cantons to provide equal homework scaffolding.',
    limitations: 'Centralized curriculum models risk stifling teacher instructional autonomy if institutional evaluation metrics become overly standardized.',
    tags: ['digital sovereignty', 'equity', 'public infrastructure', 'governance', 'illustrative demo'],
    status: 'candidate'
  },
  {
    id: 'demo-8',
    title: 'Decentralized Student Skill Credentialing Ledger',
    summary: 'A verifiable open-standards cryptographic badge protocol issued directly by vocational master craftspeople upon in-person workshop artifact verification.',
    source_url: '#',
    source_name: 'Illustrative demonstrator scenario — not a verified innovation record',
    source_type: 'illustrative_demo',
    published_at: null,
    discovered_at: '2026-09-29T10:40:00Z',
    country: 'Estonia',
    country_code: 'EE',
    city: 'Tallinn',
    latitude: 59.437,
    longitude: 24.7536,
    innovation_type: 'Credentialing',
    educational_problem: 'Traditional paper certificates cannot represent micro-competencies and dynamic master-level technical capabilities in fast-evolving trades.',
    target_groups: ['Vocational Education', 'Lifelong Learning'],
    novelty: 3,
    maturity: 'pilot',
    evidence_level: 'none',
    evidence_summary: 'Synthetic scenario used to exercise geography, clustering, filtering and Innovation Profile UI. It is not a verified research finding and must not be cited as evidence.',
    swiss_relevance: 'Strong resonance with the Swiss dual VET system (SBFI / Oda) looking to supplement federal certificates (EFZ) with dynamic modular credentials.',
    swiss_application_hypothesis: 'Pilot verifiable digital workshop credentials for precision manufacturing apprentices in the Biel/Seeland watchmaking cluster.',
    limitations: 'Requires sustained industry stakeholder consensus on competence taxonomies; vulnerable to credential inflation.',
    tags: ['vocational', 'micro-credentials', 'Berufslehre', 'verification', 'illustrative demo'],
    status: 'candidate'
  },
  {
    id: 'demo-9',
    title: 'Offline-First Solar Mesh Classroom Assistant',
    summary: 'A ruggedized micro-server running compact language models powered by mini solar panels, broadcasting local Wi-Fi curriculum caches and voice tutoring to remote classrooms without internet access.',
    source_url: '#',
    source_name: 'Illustrative demonstrator scenario — not a verified innovation record',
    source_type: 'illustrative_demo',
    published_at: null,
    discovered_at: '2026-09-20T12:00:00Z',
    country: 'Kenya',
    country_code: 'KE',
    city: 'Nairobi',
    latitude: -1.2921,
    longitude: 36.8219,
    innovation_type: 'Learning Environment',
    educational_problem: 'Global digital education tools assuming uninterrupted broadband and reliable electrical grids, excluding millions of rural learners.',
    target_groups: ['Primary', 'Sekundarstufe I'],
    novelty: 5,
    maturity: 'pilot',
    evidence_level: 'none',
    evidence_summary: 'Synthetic scenario used to exercise geography, clustering, filtering and Innovation Profile UI. It is not a verified research finding and must not be cited as evidence.',
    swiss_relevance: 'Inspiring architecture for emergency education, outdoor school weeks (Waldschule / Schulverlegungen), and Swiss development cooperation projects.',
    swiss_application_hypothesis: 'Utilize ruggedized offline edge nodes during alpine outdoor learning expeditions where cellular reception is unavailable.',
    limitations: 'Battery lifecycle management in harsh climates and logistical overhead in updating local offline model weights.',
    tags: ['offline-first', 'edge computing', 'equity', 'resilient infrastructure', 'illustrative demo'],
    status: 'candidate'
  },
  {
    id: 'demo-10',
    title: 'Immersive Teaching Simulator',
    summary: 'A PHBern-led virtual-reality teaching simulator that lets pre-service educators practise noticing and coping with classroom disruptions in lifelike pedagogical situations.',
    source_url: 'https://www.phbern.ch/belearn/aktivitaeten/projektfoerderung-belearn/immersive-teaching-simulator',
    source_name: 'PHBern / BeLEARN — Immersive Teaching Simulator',
    source_type: 'research_project',
    published_at: null,
    discovered_at: '2026-10-02T09:00:00Z',
    country: 'Switzerland',
    country_code: 'CH',
    city: 'Bern',
    latitude: 46.948,
    longitude: 7.4474,
    innovation_type: 'Teacher Education',
    educational_problem: 'Teacher trainees experiencing overwhelming reality shock in early practicums due to insufficient safe opportunities to practice de-escalation strategies.',
    target_groups: ['Teacher Education', 'School Leadership'],
    novelty: 5,
    maturity: 'pilot',
    evidence_level: 'emerging',
    evidence_summary: 'PHBern/BeLEARN report a pilot with two measurement points and a general improvement in participants’ ability to perceive classroom disruptions after training. Further results were still pending on the public project page; no effect size is asserted here.',
    swiss_relevance: 'Primary domestic anchor project within the Canton Bern teacher education landscape, directly addressing teacher retention and practicum readiness.',
    swiss_application_hypothesis: 'Embed the synthetic classroom simulator into the second-year PHBern practicum preparation module before school placement.',
    limitations: 'Simulated behavioral cues lack the subtle somatic and emotional nuances of real children; requires skilled human facilitator debriefs.',
    tags: ['teacher education', 'PHBern', 'simulation', 'classroom management'],
    status: 'candidate'
  },
  {
    id: 'demo-11',
    title: 'Sovereign Open Source Teacher Lesson Co-Planner',
    summary: 'A privacy-first desktop application that runs open-weights models locally to assist teachers with syllabus-aligned lesson planning, rubrics, and differentiated worksheet synthesis without cloud telemetry.',
    source_url: '#',
    source_name: 'Illustrative demonstrator scenario — not a verified innovation record',
    source_type: 'illustrative_demo',
    published_at: null,
    discovered_at: '2026-09-27T15:20:00Z',
    country: 'Germany',
    country_code: 'DE',
    city: 'Kiel',
    latitude: 54.3233,
    longitude: 10.1228,
    innovation_type: 'Teacher Support',
    educational_problem: 'Teachers spending up to 15 hours weekly on administrative lesson formatting while facing severe legal ambiguities regarding student data in commercial US AI clouds.',
    target_groups: ['Primary', 'Sekundarstufe I', 'Sekundarstufe II'],
    novelty: 3,
    maturity: 'scaling',
    evidence_level: 'none',
    evidence_summary: 'Synthetic scenario used to exercise geography, clustering, filtering and Innovation Profile UI. It is not a verified research finding and must not be cited as evidence.',
    swiss_relevance: 'Directly compatible with Swiss cantonal data protection acts (Kantonale Datenschutzgesetze) and cantonal teacher workload relief goals.',
    swiss_application_hypothesis: 'Bundle cantonal Lehrplan 21 competenties into local open model context templates for Bernese primary school teachers.',
    limitations: 'Local inference speed is constrained by school hardware specifications (requires Apple Silicon or modern GPUs for smooth token generation).',
    tags: ['teacher support', 'open source', 'local AI', 'Lehrplan 21', 'illustrative demo'],
    status: 'candidate'
  },
  {
    id: 'demo-12',
    title: 'Interactive Multi-Modal Mathematical Argumentation Sandbox',
    summary: 'A visual proof workbench that converts abstract algebraic theorems into dynamic geometrical physics simulations, demanding that learners explain step-by-step causal mechanisms to advance.',
    source_url: '#',
    source_name: 'Illustrative demonstrator scenario — not a verified innovation record',
    source_type: 'illustrative_demo',
    published_at: null,
    discovered_at: '2026-09-22T08:45:00Z',
    country: 'United Kingdom',
    country_code: 'GB',
    city: 'Cambridge',
    latitude: 52.2053,
    longitude: 0.1218,
    innovation_type: 'Pedagogy',
    educational_problem: 'Students memorizing formulas for standardized tests without developing intuitive geometric intuition or mathematical argumentation skills.',
    target_groups: ['Sekundarstufe I', 'Sekundarstufe II'],
    novelty: 4,
    maturity: 'pilot',
    evidence_level: 'none',
    evidence_summary: 'Synthetic scenario used to exercise geography, clustering, filtering and Innovation Profile UI. It is not a verified research finding and must not be cited as evidence.',
    swiss_relevance: 'High value for Sek I/II mathematics curricula aiming to build lasting STEM interest before Gymnasium entry.',
    swiss_application_hypothesis: 'Test whether visual argumentation sandboxes reduce the gender gap in mathematics confidence in Bernese Sekundarschulen.',
    limitations: 'Requires teacher professional development to integrate effectively; some learners can get distracted by gamified physics mechanics.',
    tags: ['mathematics', 'conceptual understanding', 'visual proof', 'STEM', 'illustrative demo'],
    status: 'candidate'
  }
];

export const demoRelations: RadarRelation[] = [
  {
    id: 'rel-1',
    from_signal_id: 'demo-4', // EPFL Socratic Sparring
    to_signal_id: 'demo-10', // PHBern Synthetic Classroom
    relation_type: 'similar_to',
    confidence: 0.5,
    rationale: 'Illustrative relationship for demonstrator UI — Both leverage adversarial or multi-persona synthetic agents to foster critical human reflection and meta-cognitive debate in Swiss higher education.'
  },
  {
    id: 'rel-2',
    from_signal_id: 'demo-1', // Campus as AI Sandbox
    to_signal_id: 'demo-2', // Mission-based skills studio
    relation_type: 'same_cluster',
    confidence: 0.5,
    rationale: 'Illustrative relationship for demonstrator UI — Shared pedagogical premise: replacing passive multiple-choice compliance with authentic physical or digital artifacts generated in living environments.'
  },
  {
    id: 'rel-3',
    from_signal_id: 'demo-3', // Image-First Early Literacy
    to_signal_id: 'demo-6', // Continuous Speech Assessment
    relation_type: 'related_to',
    confidence: 0.5,
    rationale: 'Illustrative relationship for demonstrator UI — Complementary approaches targeting low-abstraction sensory-first language acquisition in early childhood and multilingual learner groups.'
  },
  {
    id: 'rel-4',
    from_signal_id: 'demo-7', // Singapore National Open AI Tutor
    to_signal_id: 'demo-11', // German Open Source Lesson Planner
    relation_type: 'same_cluster',
    confidence: 0.5,
    rationale: 'Illustrative relationship for demonstrator UI — Both represent public-sector, sovereign infrastructure movements resisting commercial vendor data capture in compulsory education.'
  },
  {
    id: 'rel-5',
    from_signal_id: 'demo-5', // Adaptive Cognitive Load
    to_signal_id: 'demo-12', // Multi-Modal Mathematical Sandbox
    relation_type: 'related_to',
    confidence: 0.5,
    rationale: 'Illustrative relationship for demonstrator UI — Both focus on mitigating cognitive overload and fostering deep conceptual understanding in secondary mathematics through dynamic scaffolding.'
  },
  {
    id: 'rel-6',
    from_signal_id: 'demo-8', // Estonian Skill Credentialing
    to_signal_id: 'demo-2', // Mission-based skills studio
    relation_type: 'evolved_into',
    confidence: 0.5,
    rationale: 'Illustrative relationship for demonstrator UI — Estonian micro-credentialing provides the verifiable credential layer for artifact-centric mission curricula.'
  },
  {
    id: 'rel-7',
    from_signal_id: 'demo-9', // Offline Solar Mesh
    to_signal_id: 'demo-11', // Local Lesson Planner
    relation_type: 'similar_to',
    confidence: 0.5,
    rationale: 'Illustrative relationship for demonstrator UI — Both address digital sovereignty and privacy via localized on-device inference, bypassing cloud dependence.'
  }
];

export const demoReviews: RadarReview[] = [];

export const demoClusters: RadarCluster[] = [
  {
    id: 'cluster-1',
    title: 'Learning Environments as Living Labs',
    subtitle: 'Physical infrastructure transformed into programmable student inquiry sandboxes',
    description: 'Demonstration cluster assembled from the current mixed demo dataset to show how related signals could be grouped. It is not evidence of an observed international movement.',
    signalsCount: 3,
    signalIds: ['demo-1', 'demo-9', 'demo-2'],
    primaryGeography: ['Japan', 'United States', 'Kenya'],
    educationalImpact: 'Demonstration hypothesis: authentic infrastructure could connect STEM concepts with real-world ecological feedback and student inquiry.',
    emergenceType: 'independent_emergence',
    hypothesisStatus: 'provisional_hypothesis'
  },
  {
    id: 'cluster-2',
    title: 'Epistemic Agency & Adversarial AI Scaffolding',
    subtitle: 'Simulated counter-arguments and triadic dialogues countering passive AI reliance',
    description: 'Demonstration hypothesis showing how a future Radar could connect signals around AI as a sparring partner rather than an answer oracle. The cluster is illustrative until supported by verified records.',
    signalsCount: 4,
    signalIds: ['demo-4', 'demo-10', 'demo-5', 'demo-12'],
    primaryGeography: ['Switzerland', 'Australia', 'United Kingdom'],
    educationalImpact: 'Demonstration hypothesis: adversarial dialogue may shift learners from passive AI consumption toward active evaluation and argumentation.',
    emergenceType: 'independent_emergence',
    hypothesisStatus: 'provisional_hypothesis'
  },
  {
    id: 'cluster-3',
    title: 'Public Digital Sovereignty & On-Device Pedagogy',
    subtitle: 'Resisting commercial cloud lock-in through open curriculum-aligned edge infrastructure',
    description: 'Demonstration hypothesis for relating sovereign, open or local educational infrastructure. Most records in this cluster are illustrative UI scenarios, not verified initiatives.',
    signalsCount: 3,
    signalIds: ['demo-7', 'demo-11', 'demo-8'],
    primaryGeography: ['Singapore', 'Germany', 'Estonia'],
    educationalImpact: 'Demonstration hypothesis: sovereign or local infrastructure may strengthen governance, privacy and equitable public access.',
    emergenceType: 'policy_driven',
    hypothesisStatus: 'provisional_hypothesis'
  },
  {
    id: 'cluster-4',
    title: 'Sensory & Representation-First Literacy',
    subtitle: 'Grounding abstract symbols in multi-modal, physical, and acoustic experiences',
    description: 'Demonstration hypothesis for representation-first learning approaches. It exists to exercise relational analysis and is not yet a validated trend claim.',
    signalsCount: 3,
    signalIds: ['demo-3', 'demo-6', 'demo-12'],
    primaryGeography: ['India', 'Finland', 'United Kingdom'],
    educationalImpact: 'Demonstration hypothesis: representation-first approaches may lower abstraction barriers for heterogeneous learners.',
    emergenceType: 'independent_emergence',
    hypothesisStatus: 'provisional_hypothesis'
  }
];
